### ISSUE TITLE
English support?

### ISSUE THREAD

**Issue by glowingnec** [SkyD666/Rays-Android#2]
Hello, I recently stumbled upon this app on Github and I just want to say: Your app looks and works great!
Do you have plan for English support in the future?

**Comment by SkyD666** [comment]
Thank you for your support, I will join English support in the future!

**Comment by SkyD666** [comment]
Hi, English support has now been added, please try the attached zip file below. Since I'm not very good at English, there may be some parts of the translation that are not authentic enough, so please point them out if you'd like. Thank you! 🤗

[app_release_github_1.1-rc03.zip](https://github.com/SkyD666/Rays-Android/files/11524782/app_release_github_1.1-rc03.zip)

**Comment by glowingnec** [comment]
The translation is really good, there are some minor errors but I think it won't affect the experience at all~
Thanks you so so so much!

**Comment by SkyD666** [comment]
English Readme: 

https://github.com/SkyD666/Rays-Android/blob/master/doc/README/README-en.md
